export const ERROR_CODES = [
  'VALIDATION_ERROR', 'UNAUTHORIZED', 'FORBIDDEN', 'NOT_FOUND', 'EMAIL_TAKEN',
  'INVALID_CREDENTIALS', 'RATE_LIMITED', 'DAILY_LIMIT', 'REGEN_LIMIT_REACHED', 'POSTER_BUSY',
  'CONTENT_BLOCKED', 'UNSUPPORTED_IMAGE', 'IMAGE_TOO_SMALL', 'FILE_TOO_LARGE', 'PHOTO_NOT_OWNED',
  'TEMPLATE_UNAVAILABLE', 'INTERNAL', 'SLUG_TAKEN',
  'UPGRADE_REQUIRED', 'PLAN_DOWNGRADE', 'PAYMENT_FAILED', 'PAYMENT_CLOSED', 'POSTER_NOT_READY',
  'POSTER_UNDER_REVIEW', 'POSTER_REJECTED', 'POSTER_NOT_PENDING',
] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];

export interface ApiErrorBody {
  error: { code: ErrorCode; message: string; details?: unknown };
}
